# Generated by Django 2.2.6 on 2019-10-27 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0003_customer'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Customer',
        ),
    ]
